### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by shashi-netra** [PKU-YuanGroup/Video-LLaVA#10]
> The majority of this project is released under the Apache 2.0 license as found in the [LICENSE](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/LICENSE) file.
> 
> The service is a research preview intended for non-commercial use only, subject to the model [License](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md) of LLaMA, [Terms of Use](https://openai.com/policies/terms-of-use) of the data generated by OpenAI, and [Privacy Practices](https://chrome.google.com/webstore/detail/sharegpt-share-your-chatg/daiacboceoaocpibfodeljbdfacokfjb) of ShareGPT. Please contact us if you find any potential violation.

Could you confirm what the service is referring to? The gradio UI or is the model under Apache 2.0 license which allows for commercial use afaik.

**Comment by JessyTsu1** [comment]
The model used in this project is built upon Vicuna 1.5, which in turn is based on LLaMA 2. Therefore, we inherit the weight licensing protocol from LLaMA 2, making both the weights and code open source.

This means that the model and its associated weights are indeed available under the Apache 2.0 license, which permits commercial use. Thx
