### ISSUE TITLE
Invalid link to MoE-LLaVA

### ISSUE THREAD

**Issue by DDVD233** [PKU-YuanGroup/Video-LLaVA#116]
The link on readme to MoE-LLaVA (https://github.com/PKU-YuanGroup/MoE-LLaVA/blob/main/MoE-LLaVA.pdf) is invalid. It does link to the correct repo, but there is no MoE-LLaVA.pdf. 
<img width="580" alt="image" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/16710181/6e9a5a85-bc61-4754-993d-b0614643f592">

**Comment by LinB203** [comment]
Thanks, fixed that.

**Comment by DDVD233** [comment]
Thanks!
