### ISSUE TITLE
推理过程中出现错误

### ISSUE THREAD

**Issue by zhangye0402** [PKU-YuanGroup/Video-LLaVA#117]
<img width="791" alt="屏幕截图 2024-02-28 150612" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/103350812/5e5a40be-b736-479d-81ad-4dee70a52ea1">
<img width="794" alt="屏幕截图 2024-02-28 150644" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/103350812/c12d9d13-b270-42f6-8bfa-a0faa4f183b0">
在推理过程中出现了如下报错，我修改了model_path到本地地址，同时修改了权重文件中的config.json中的mm_image_tower 以及 mm_video_tower 到本地地址，之后在推理中出现了图片上显示错误，请问我该如何修改才能正确运行video-llava？万分感谢！

**Comment by zhangye0402** [comment]
我的，我翻到解决办法了

**Comment by qingchunlizhi** [comment]
> 我的，我翻到解决办法了

你是怎么解决的

**Comment by liury889** [comment]
同问，我一样的问题
