### ISSUE TITLE
can not find preprocessor_config.json in LanguageBind_Image

### ISSUE THREAD

**Issue by SKBL5694** [PKU-YuanGroup/Video-LLaVA#12]
When I tried to deploy the project on hf locally, I couldn't connect to huggingface, so I pre-downloaded LanguageBind_image, video-llava-7B and LanguageBind_video_image locally, and set model_path = 'local_path/LanguageBind/ in app.py Video-LLaVA-7B/',
And change mm_image_tower and mm_video_tower in llava7B's config.json to local paths. But eventually I got this error at runtime.
local_path/LanguageBind/LanguageBind_Image does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//local_path/LanguageBind/LanguageBind_Image/main' for available files
I think this error means that the preprocessor_config.json file was not found in LanguageBind_Image. However, I did not find this file in the corresponding location of huggingface. Did I make a mistake?

**Comment by YuanJianhao508** [comment]
> When I tried to deploy the project on hf locally, I couldn't connect to huggingface, so I pre-downloaded LanguageBind_image, video-llava-7B and LanguageBind_video_image locally, and set model_path = 'local_path/LanguageBind/ in app.py Video-LLaVA-7B/', And change mm_image_tower and mm_video_tower in llava7B's config.json to local paths. But eventually I got this error at runtime. local_path/LanguageBind/LanguageBind_Image does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//local_path/LanguageBind/LanguageBind_Image/main' for available files I think this error means that the preprocessor_config.json file was not found in LanguageBind_Image. However, I did not find this file in the corresponding location of huggingface. Did I make a mistake?

Hey dude, encounter the same issue in training offline as well. Did you manage to solve it?

**Comment by wuyinglong123** [comment]
nice

**Comment by PHI6kai** [comment]
我按照您的这些步骤将该下载的下好之后发现，会模型异常的错误，请问是什么原因
Some weights of the model checkpoint at LanguageBind/Video-LLaVA-7B were not used when initializing
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/50110789/57d10ab3-e1fb-49e2-bf68-1c4c6b3c0d07)
@LinB203
