### ISSUE TITLE
How should I obtain llava_image_tune_.json, videochatgpt_tune_.json, and nlp_tune.json

### ISSUE THREAD

**Issue by Annie1900** [PKU-YuanGroup/Video-LLaVA#130]
Excuse me, I am looking to fine-tune the video-llava model, and I noticed that the finetune.sh file mentions three JSON files, but the downloaded dataset only contains videos. Could you advise on how I can obtain these JSON files? Thank you.
![微信图片_20240315102818](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/73414003/e0e624a1-4a0b-4fc3-9bd1-86446cae2677)

**Comment by laurenlong** [comment]
Hi, have you solved this problem yet, I'm experiencing the same problem.
