### ISSUE TITLE
Error of multi-turn conversations

### ISSUE THREAD

**Issue by yujiangpu20** [PKU-YuanGroup/Video-LLaVA#14]
Thank you for your great work! I tried some of the sample videos provided, but the model doesn't seem to support multi-turn conversations. The error is triggered when I try to send the second question. Does it only support a single round at this stage?

**Comment by LinB203** [comment]
Did you test it with the demo on huggingface?

**Comment by yujiangpu20** [comment]
Yes. I just tried the demo and it failed for multi-turn conversations. My second question is 'What color is the baby's T-shirt?'
<img width="1330" alt="截屏2023-11-27 20 38 17" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/51237784/25283db4-9f82-470f-9f09-63fb8d6e09c0">

**Comment by LinB203** [comment]
I checked the log and it's because of OOM. Maybe you can run it locally with more memory.

**Comment by yujiangpu20** [comment]
Got it. Thanks for your kind response!

**Comment by LinB203** [comment]
BTW.

**Comment by LinB203** [comment]
BTW.
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/62638829/99549738-821b-4bcb-9845-168f69659966)
