### ISSUE TITLE
Unable to install flash attn module

### ISSUE THREAD

**Issue by anantalp** [PKU-YuanGroup/Video-LLaVA#143]
(videollava) [evuser1 video_llava]$ pip install flash-attn --no-build-isolation > flash_attn_error.log
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: -11
  ╰─> [110 lines of output]
      OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 20 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 23 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 24 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 25 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 26 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 27 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 28 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 29 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 30 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 32 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 33 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 34 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 35 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 36 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 45 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 48: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 105 current, 105 max
      fatal: Not a git repository (or any of the parent directories): .git
      /tmp/pip-install-l87_wa65/flash-attn_76ead9c5ea5f4657a32f06bbec6baa4e/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l87_wa65/flash-attn_76ead9c5ea5f4657a32f06bbec6baa4e/setup.py", line 134, in <module>
          CUDAExtension(
        File "/home/cap6412.student16/anaconda3/envs/videollava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1048, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/cap6412.student16/anaconda3/envs/videollava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/cap6412.student16/anaconda3/envs/videollava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2223, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.0.1+cu117
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Ishtiaque-khan97** [comment]
Hi, how did you solve this issue?
@anantalp
