### ISSUE TITLE
[Question] Would it be possible to provide which 8 frames Video-LLaVA should use?

### ISSUE THREAD

**Issue by olcaybuyan** [PKU-YuanGroup/Video-LLaVA#17]
If I read your paper correctly, you're only using 8 frames of a video? Would it be possible to specify which 8 frames to use instead of just using the first 8 frames?

**Comment by SidHard** [comment]
https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/llava/model/multimodal_encoder/languagebind/video/processing_video.py#L101

**Comment by olcaybuyan** [comment]
Thanks

**Comment by TousakaNagio** [comment]
@LinB203 I am wandering when will you release the next version? Thanks!

**Comment by LinB203** [comment]
> @LinB203 I am wandering when will you release the next version? Thanks!

Conservative estimate, about next month.

**Comment by fightingaaa** [comment]
> Change `decord` to `opencv` and adjust the `frame_id_list`. We will provide more flexible codes and a strong video-llm in next version.

请问是通过增加frame token的方式，但是固定frame 数量。但是指 固定fps 方式，frame数量可变呢
