### ISSUE TITLE
Some weights of the model checkpoint at LanguageBind/Video-LLaVA-7B were not used when initializing 

### ISSUE THREAD

**Issue by PHI6kai** [PKU-YuanGroup/Video-LLaVA#18]
我采用您代码中可以本地调用模型运行的方式，下载好llava7b、languageBindImage和LanguageBindVideo，但是报如下错误
Some weights of the model checkpoint at LanguageBind/Video-LLaVA-7B were not used when initializing LlavaLlamaForCausalLM: ['model.video_tower.video_tower.encoder.layers.19.temporal_layer_norm1.weight', 'model.image_tower.image_tower.encoder.layers.13.mlp.fc1.bias', 'model.video_tower.video_tower.encoder.layers.11.temporal_attn.k_proj.weight', 'model.image_tower.image_tower.encoder.layers.19.mlp.fc1.weight', 'model.video_tower.video_tower.encoder.layers.2.temporal_attn.k_proj.weight', 'model.video_tower.video_tower.encoder.layers.17.temporal_attn.k_proj.bias', 'model.image_tower.image_tower.encoder.layers.12.self_attn.out_proj.weight', 'model.video_tower.video_tower.encoder.layers.21.self_attn.out_proj.weight'
还有一段代码报错，最后输出
LlavaLlamaForCausalLM: ['model.video_tower.video_tower.encoder.layers.19.temporal_layer_norm1.weight', 'model.image_tower.image_tower.encoder.layers.13.mlp.fc1.bias', 'model.video_tower.video_tower.encoder.layers.11.temporal_attn.k_proj.weight', 'model.image_tower.image_tower.encoder.layers.19.mlp.fc1.weight', 'model.video_tower.video_tower.encoder.layers.2.temporal_attn.k_proj.weight', 'model.video_tower.video_tower.encoder.layers.17.temporal_attn.k_proj.bias', 'model.image_tower.image_tower.encoder.layers.12.self_attn.out_proj.weight', 'model.video_tower.video_tower.encoder.layers.21.self_attn.out_proj.weight'

**Comment by LinB203** [comment]
这只是警告，因为video/image encoder的权重在LLM初始化之后再加载。你可以接着进行测试一个视频，查看输出是否是正常对话。

**Comment by PHI6kai** [comment]
> [Chinese] 这只是警告，因为video/image encoder的权重在LLM初始化之后再加载。你可以接着进行测试一个视频，查看输出是否是正常对话。 [En] This is just a warning, as the video/image encoder weights are loaded after LLM is initialised. You can then proceed to test a video to see if the output is normal dialogue.

![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/50110789/57994dc7-46b8-45ee-916a-c5d49279cca4)
后面直接报错，无法运行，如果只是警告的话其实是可以运行的吧

**Comment by sunwhw** [comment]
I also encountered this problem. Have you solved it？

> > [Chinese] 这只是警告，因为video/image encoder的权重在LLM初始化之后再加载。你可以接着进行测试一个视频，查看输出是否是正常对话。 [En] This is just a warning, as the video/image encoder weights are loaded after LLM is initialised. You can then proceed to test a video to see if the output is normal dialogue.
> 
> ![image](https://private-user-images.githubusercontent.com/50110789/286471713-57994dc7-46b8-45ee-916a-c5d49279cca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNTIzNDAsIm5iZiI6MTcwNjM1MjA0MCwicGF0aCI6Ii81MDExMDc4OS8yODY0NzE3MTMtNTc5OTRkYzctNDZiOC00NWVlLTkxNmEtYzVkNDkyNzljY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDEwNDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDI2ZjcwMGU3NmFhMjUyZmE0ZjFjMTkzNzgwYjE1Nzg5OTFiY2Y5NTllZjlmZTFhZTBjMTMxYmFhMDRhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWJtV4fQTHGAeToSiB9T_4JTFGT6qAJ4xrjReLaz3IA) 后面直接报错，无法运行，如果可以运行我也不会问这些 @LinB203
