### ISSUE TITLE
missing file: preprocessor_config.json 

### ISSUE THREAD

**Issue by JunanPan** [PKU-YuanGroup/Video-LLaVA#186]
When I try: 
processor = VideoLlavaProcessor.from_pretrained("LanguageBind/Video-LLaVA-7B") 

I got:
OSError: LanguageBind/Video-LLaVA-7B does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/LanguageBind/Video-LLaVA-7B/tree/main' for available files.

**Comment by ShoiLyaung** [comment]
How did you solve it?

**Comment by LIU020174** [comment]
How did you solve it?
