### ISSUE TITLE
Q：她们乒乓球打得好吗？

### ISSUE THREAD

**Issue by adaaaaaa** [PKU-YuanGroup/Video-LLaVA#19]
A：她们乒乓球打得很好，她们的手指灵活，乒乓球一次都没有错过目标。

from：https://replicate.com/nateraw/video-llava?prediction=p4qnq7dbin6msnwk77b3odfjna

**Comment by LinB203** [comment]
Anything I miss?

**Comment by LinB203** [comment]
Inactive, close it.

**Comment by adaaaaaa** [comment]
> Anything I miss?

![图片](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/23206387/2c952302-a5db-45a1-bcd2-963c8b19cefd)
