### ISSUE TITLE
always answer yes？

### ISSUE THREAD

**Issue by RalphHan** [PKU-YuanGroup/Video-LLaVA#20]
When I ask, "is there any \<some-object\> in the video?", the model always answers "yes".

**Comment by wolfworld6** [comment]
hello，have you solved it？

**Comment by RalphHan** [comment]
No, it might be the overfitting of the model.

**Comment by LinB203** [comment]
The reason for this is most likely because of the video instruction dataset, for which we are about to release a more robust model.

**Comment by xmy0916** [comment]
> No, it might be the overfitting of the model.

due to my test, the performance loss of language models is very serious. i think the vision llm must eval on some pure language dataset to make sure keeping the source performance.
