### ISSUE TITLE
What version of flash_attn do I need to run finetune.sh?

### ISSUE THREAD

**Issue by dhatchi711** [PKU-YuanGroup/Video-LLaVA#204]
I tried pip install flash-attn --no-build-isolation. It has been running for the last 1.5 hours. Is there something I need to do? I have ninja, cuda, torch all installed according to the readme.

Or is there a way I can directly download the correct version whl file from [https://github.com/Dao-AILab/flash-attention/releases?page=1]?

**Comment by dhatchi711** [comment]
Found a workaround

**Comment by itsjustfons** [comment]
Hi, I'm stuck at getting flash attention. What was your workaround?

**Comment by maggieHao** [comment]
Same issue here. May I ask what workaround you’re using? @dhatchi711
