### ISSUE TITLE
为什么本地加载模型也报huggingface的错误

### ISSUE THREAD

**Issue by HAOYON-666** [PKU-YuanGroup/Video-LLaVA#205]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like LanguageBind/LanguageBind_Image is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by HAOYON-666** [comment]
为什么模型文件都下载到本地了还是一直报无法连接huggingface，为什么
还需要连接huggingface

**Comment by HAOYON-666** [comment]
请问都需要具体下载哪些模型文件，是模型文件没有下载完整吗

**Comment by Ghuipeng** [comment]
you need to download the model of LanguageBind/LanguageBind_Image and LanguageBind/LanguageBind_video and then fix the config.
