### ISSUE TITLE
multiple questions for multiple videos

### ISSUE THREAD

**Issue by YajieW99** [PKU-YuanGroup/Video-LLaVA#24]
Hello! When I try to implement multiple questions for multiple videos, there's some errors:

It seems that the current prompt doesn't contain the previous answer, and there's an error in the llava/model/llava_arch.py
![Snipaste_2023-12-01_11-58-17](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/44310850/776f149f-f154-4e5a-833d-d995dad2be53)
![Snipaste_2023-12-01_11-50-41](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/44310850/bae50660-4541-4a60-af33-f9026e78dc9e)

Would you provide an inference demo for multiple questions && multiple videos? Thanks!

Also, here is my multiple questions inference demo for multiple videos, please point out the problem.

    `while True:
        try:
            video = input('Input video path: ')
        except:
            print('Input error, try again.')
            continue
        else:
            if video == 'exit':
                print('Goodbye!')
                break
            if not os.path.exists(video):
                print('{} not exist, try again.'.format(video))
                continue

        video_tensor = video_processor(video, return_tensors='pt')['pixel_values']
        if type(video_tensor) is list:
            tensor = [video.to(model.device, dtype=torch.float16) for video in video_tensor]
        else:
            tensor = video_tensor.to(model.device, dtype=torch.float16)

        while True:
            try:
                inp = input('User: ')
            except:
                print('Input error, try again.')
                continue
            else:
                if inp == 'exit':
                    break
                else:
                    # print(f"{roles[1]}: {inp}")
                    inp = DEFAULT_X_TOKEN['VIDEO'] + '\n' + inp
                    conv.append_message(conv.roles[0], inp)
                    conv.append_message(conv.roles[1], None)

                    prompt = conv.get_prompt() # 同一视频，多个问题时，不包含上个问题答案；不同视频时，之前的提问内容不清空
                    input_ids = tokenizer_X_token(prompt, tokenizer, X_TOKEN_INDEX['VIDEO'], return_tensors='pt').unsqueeze(0).cuda()
                    stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
                    keywords = [stop_str]
                    stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)

                    with torch.inference_mode():
                        output_ids = model.generate(
                            input_ids,
                            images=[tensor, key],
                            do_sample=True,
                            temperature=0.1,
                            max_new_tokens=1024,
                            use_cache=True,
                            stopping_criteria=[stopping_criteria])

                    outputs = tokenizer.decode(output_ids[0, input_ids.shape[1]:]).strip()
                    print(outputs)`

**Comment by LinB203** [comment]
We will add this feature in the next version.
