### ISSUE TITLE
[Q] local demo problem multi-turn dialogue

### ISSUE THREAD

**Issue by DimplesL** [PKU-YuanGroup/Video-LLaVA#25]
In the multi-turn dialogue, it appears that the video is being passed multiple times, leading to crashes in GPU memory. How can this be resolved? Does it support multiple turns of dialogue with the same video?

**Comment by SKBL5694** [comment]
I also encountered the same problem, and I found that when the conversation reaches the third round (as the memory can only support up to the third round), the output results mostly turn into some chaotic characters.Such as:
"[
[

[ [ [ [

and.

d.

[
..."

**Comment by LinB203** [comment]
Yes, as we have not trained on multi round conversations about videos, we currently do not support it.

But in the next version, we will upgrade it.
