### ISSUE TITLE
This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint

### ISSUE THREAD

**Issue by wolfworld6** [PKU-YuanGroup/Video-LLaVA#29]
Thank you very much for your great work, when I run locally，Igot this message：
- This IS expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

but，Different images, the same output result，why？

**Comment by LinB203** [comment]
If this is a warning, then it can be ignored.
