### ISSUE TITLE
Video checkpoint is broken

### ISSUE THREAD

**Issue by NoSavedDATA** [PKU-YuanGroup/Video-LLaVA#3]
I've run the requirements installation, but the model spits out random words when I run the video examples from gradio.
The image captioning works fine.
The hugging face demo for video captioning works fine as well.

**Comment by LinB203** [comment]
Sorry for that. I'll check and fix it.

**Comment by LinB203** [comment]
Now it is available!

**Comment by wjfwjfwjf** [comment]
还是不能用
