### ISSUE TITLE
一个sample是一个model 是指的什么意思呢

### ISSUE THREAD

**Issue by fightingaaa** [PKU-YuanGroup/Video-LLaVA#31]
在Video-LLaVA/llava/model/llava_arch.py 文件中364-367行代码的理解
这段话中，一个sample是一个model 是指的什么意思呢，对应 一个batch 中一个sample吗？
`                cur_X_idx += 1 ############## 注意这里跳过了，如果一个sample是一个modal，那么就跳过1个全zero的modal，如果一个sample对应多个modal，这里的训练逻辑不对！！！
                ###### 但似乎不影响1个sample的inference
                ###### 一个text对应视频和图片，直接走下边了。只有1个text，传入none或者1个/2个全zero都无所谓，反正没有下一个数据了。
                continue`

**Comment by fightingaaa** [comment]
<img width="1347" alt="截屏2023-12-05 17 54 39" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/35753204/082d2991-42d4-4d13-a18d-54453fe54076">

**Comment by LinB203** [comment]
抱歉这是刚开始时候的一些遗留。已经删除。
[En] Sorry, that's typo, we fixed it.

**Comment by LinB203** [comment]
删除注释。
[En] We have deleted comment.

> > 抱歉这是刚开始时候的一些遗留。已经删除。 [En] Sorry, that's typo, we fixed it.
> > 你好，是只需要删除注释吗。还是说那个continue 也要删掉

**Comment by fightingaaa** [comment]
> 删除注释。 [En] We have deleted comment.
> 
> > > 抱歉这是刚开始时候的一些遗留。已经删除。 [En] Sorry, that's typo, we fixed it.
> > > 你好，是只需要删除注释吗。还是说那个continue 也要删掉

好的。多谢。还请教下，我在跑 scripts/v1_5/finetune.sh代码时报 显存不足。使用的1卡 A100-80g

**Comment by LinB203** [comment]
I actually had this problem, but when I increased the number of GPUs (batch size per GPU remained the same), the problem was solved.
Maybe you can try `zero3_offload.json`.
I think it should have something to do with deepspeed.
