### ISSUE TITLE
Cannot reproduce Zero-shot Video-QA (MSVD)

### ISSUE THREAD

**Issue by dcahn12** [PKU-YuanGroup/Video-LLaVA#34]
Thanks for your contribution!

I tried to reproduce your result (Zero-shot VideoQA on MSVD dataset) with the pretrained weight [https://huggingface.co/LanguageBind/Video-LLaVA-7B/tree/main](https://huggingface.co/LanguageBind/Video-LLaVA-7B/tree/main).

But the result is completely different from your paper.
(Reproduced result is shown below)
![2023-12-07_20-16-35](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/61134923/ab338266-9437-46b7-855e-67c077e90f79)

Can you check this?

**Comment by xmy0916** [comment]
@dcahn12 how about other video benchmarks ?

**Comment by xmy0916** [comment]
> Thanks for your contribution!
> 
> I tried to reproduce your result (Zero-shot VideoQA on MSVD dataset) with the pretrained weight https://huggingface.co/LanguageBind/Video-LLaVA-7B/tree/main.
> 
> But the result is completely different from your paper. (Reproduced result is shown below) ![2023-12-07_20-16-35](https://private-user-images.githubusercontent.com/61134923/288739292-ab338266-9437-46b7-855e-67c077e90f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODk1MDEsIm5iZiI6MTcwNjA4OTIwMSwicGF0aCI6Ii82MTEzNDkyMy8yODg3MzkyOTItYWIzMzgyNjYtOTQzNy00NmI3LTg1NWUtNjdjMDc3ZTkwZjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA5NDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2OGE2MDhlOTg1YzM5OTdiMGRlYjU3NDNmODNhYzBhZjBiZDFkOGYwZDNlZDM4NWIwN2VkOTRiMDk5MDY1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.krCLhxCKx6XoXhU83XS8Nz7fSWGXXS0y9p7pMI5cSDc)
> 
> Can you check this?

My test results on MSVD:
```
Yes count: 4041
No count: 9116
Accuracy: 0.30713688530820094
Average score: 2.726077373261382
```
