### ISSUE TITLE
why there are pure NLP conversation in videochatgpt_llavaimage_tune.json

### ISSUE THREAD

**Issue by valencebond** [PKU-YuanGroup/Video-LLaVA#39]
like dict as follows. Is it to just finetune LLM ?

> {'id': '740000',
>   'model': '',
>   'conversations': [{'from': 'human',
>     'value': '将下面的生活场景润色成动画片的对话，句数不少于8句，要求内容有教育意义\n家庭晚会\n爸爸：今晚我们举办家庭晚会，大家有什么节目表演吗？\n妈妈：我会唱一首歌，希望大家喜欢。\n哥哥：我会弹吉他，可以伴奏你唱歌。\n妹妹：我想跳一支舞，可以吗？'},
>    {'from': 'gpt',
>     'value': '(画面：家庭客厅，爸爸、妈妈、哥哥、妹妹四人围坐在沙发上)\n\n爸爸：今晚我们一家人一起举办家庭晚会，大家有什么节目表演吗？\n\n妈妈：我会唱一首歌，希望大家喜欢。 (妈妈微笑着说)\n\n哥哥：我会弹吉他，可以伴奏你唱歌。(哥哥翻起吉他，摆了一个酷酷的姿势)\n\n妹妹：我想跳一支舞，可以吗？(妹妹脸上带着期待的表情)\n\n爸爸：当然可以，你想跳哪一种舞呢？\n\n妹妹：我想跳芭蕾舞，因为我一直很喜欢看芭蕾舞演出。\n\n哥哥：那我们可以一起编排一个小节目，让妹妹跳芭蕾舞，我伴奏，妈妈唱歌。\n\n妹妹：太好了，我要开始练习了。(妹妹兴奋地跑出房间)\n\n爸爸：看到你们这么积极，我也想表演一个小魔术，让大家惊喜。\n\n妈妈：晚会不仅是娱乐，也是学习和交流的机会，我们可以通过互相表演，展示自己的才艺，同时也能增进家庭的感情，提高家人之间的沟通和合作能力。\n\n(画面：一家四口团结一致，笑容满面，享受着愉快的家庭晚会)\n\n教育意义：家庭晚会是一种增强家庭凝聚力、提高沟通能力和合作能力的好方法。通过家庭晚会，家人们可以分享自己的才艺、交流心得，加深彼此之间的了解和感情。在这个过程中，家长可以向孩子展示自己的兴趣和爱好，同时也可以从孩子身上学到新鲜事物，增加彼此之间的互动和交流。'}]

**Comment by LinB203** [comment]
As it comes initialized from the pre-trained LLM, some NLP data is added to prevent overfitting. It is common practice following [LLaVA](https://github.com/haotian-liu/LLaVA#visual-instruction-tuning).
And as stated in [issue 20](https://github.com/PKU-YuanGroup/Video-LLaVA/issues/20#issuecomment-1840261408), the performance degradation of LLM remains severe despite our addition of these NLP data overfitting. We are training a more robust version.
