### ISSUE TITLE
断点续训失败问题

### ISSUE THREAD

**Issue by dwanfun** [PKU-YuanGroup/Video-LLaVA#42]
deepspeed_load_checkpoint(self.model_wrapped, resume_from_checkpoint)
  File "/home/work/anaconda3/envs/videollava/lib/python3.10/site-packages/transformers/deepspeed.py", line 389, in deepspeed_load_checkpoint
    raise ValueError(f"Can't find a valid checkpoint at {checkpoint_path}")
ValueError: Can't find a valid checkpoint at ./checkpoints/Video-LLaVA-Pretrain-7B/checkpoint-1500
此路径下有两个文件 config.json  mm_projector.bin

**Comment by LinB203** [comment]
We reorganize the code and it support now.

**Comment by mynameischaos** [comment]
> We reorganize the code and it support now.

how to fix it, I have the same question.
