### ISSUE TITLE
 the instructions to run the demo offline

### ISSUE THREAD

**Issue by chajchaj** [PKU-YuanGroup/Video-LLaVA#44]
good job! thanks for you gays!
can you provide instructions like this:
https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/offline_demo.md

**Comment by LinB203** [comment]
Refer to [demo](https://github.com/PKU-YuanGroup/Video-LLaVA?tab=readme-ov-file#-demo)
