### ISSUE TITLE
A100 * 4 OOM

### ISSUE THREAD

**Issue by CaicaiJason** [PKU-YuanGroup/Video-LLaVA#45]
# A100 * 4 OOM  batchsize=1 的情况下仍然是OOM，好像不太合理吧，请问怎么回事呢？
这个是我的bash，大佬帮忙看下~~谢谢
```
DATA_ROOT="llava_all_image_video"
HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 CUDA_VISIBLE_DEVICES=0,1,2,3 deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path pretrain_models/vicuna-7b-v1.5 \
    --version v1 \
    --data_path ./train_anno.json \
    --video_folder ${DATA_ROOT} \
    --image_folder ${DATA_ROOT} \
    --X "Video" "Image" \
    --video_tower pretrain_models/LanguageBind_Video_merge \
    --image_tower pretrain_models/LanguageBind_Image \
    --pretrain_mm_mlp_adapter pretrain_models/Video-LLaVA-Pretrain-7B/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_x_start_end False \
    --mm_use_x_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/Video-LLaVA-7B \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 1024 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --cache_dir "./cache_dir"
```

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.30 GiB (GPU 0; 39.59 GiB total capacity; 32.86 GiB already allocated; 4.76 GiB free; 32.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by fightingaaa** [comment]
我这边 4卡A100-80g能跑起来；你可以看下 你跑的时候gpu 的显存情况

**Comment by LinB203** [comment]
我们的实验是在A100-80G上跑的，默认的训练脚本是针对于80G。但为了解决你的问题我们找了A100-40G的资源，batch
 size可以设置为4。
[En] Our experiment was run on A100-80G, the default training script is for 80G. To solve your problem we looked for A100-40G, batch size can be set to 4 for that.

**Comment by CaicaiJason** [comment]
> 我这边 4卡A100-80g能跑起来；你可以看下 你跑的时候gpu 的显存情况

就是显存突然爆了，可以看看你那边的配置吗?

**Comment by CaicaiJason** [comment]
> 我们的实验是在A100-80G上跑的，默认的训练脚本是针对于80G。但为了解决你的问题我们找了A100-40G的资源，batch size可以设置为4。 [En] Our experiment was run on A100-80G, the default training script is for 80G. To solve your problem we looked for A100-40G, batch size can be set to 4 for that.

请问你们用A100-40G，batchsize=4的情况下，是用了几张卡run呢？

**Comment by LinB203** [comment]
> > 我们的实验是在A100-80G上跑的，默认的训练脚本是针对于80G。但为了解决你的问题我们找了A100-40G的资源，batch size可以设置为4。 [En] Our experiment was run on A100-80G, the default training script is for 80G. To solve your problem we looked for A100-40G, batch size can be set to 4 for that.
> 
> 请问你们用A100-40G，batchsize=4的情况下，是用了几张卡run呢？

和你一样，4张。
[En] 4.

**Comment by CaicaiJason** [comment]
> > > 我们的实验是在A100-80G上跑的，默认的训练脚本是针对于80G。但为了解决你的问题我们找了A100-40G的资源，batch size可以设置为4。 [En] Our experiment was run on A100-80G, the default training script is for 80G. To solve your problem we looked for A100-40G, batch size can be set to 4 for that.
> > 
> > 
> > 请问你们用A100-40G，batchsize=4的情况下，是用了几张卡run呢？
> 
> 和你一样，4张。 [En] 4.

我这边确实不行A100-40G x 4的情况下，可以加个微信具体沟通下吗？
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/27617518/0d5baf1c-c6f4-4782-9ebb-d160aa9a9308)
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/27617518/d1a5b684-592c-4038-8500-df5a40ba0487)

**Comment by Lum1104** [comment]
> > > > 我们的实验是在A100-80G上跑的，默认的训练脚本是针对于80G。但为了解决你的问题我们找了A100-40G的资源，batch size可以设置为4。 [En] Our experiment was run on A100-80G, the default training script is for 80G. To solve your problem we looked for A100-40G, batch size can be set to 4 for that.
> > > 
> > > 
> > > 请问你们用A100-40G，batchsize=4的情况下，是用了几张卡run呢？
> > 
> > 
> > 和你一样，4张。 [En] 4.
> 
> 我这边确实不行A100-40G x 4的情况下，可以加个微信具体沟通下吗？ ![image](https://private-user-images.githubusercontent.com/27617518/290428642-0d5baf1c-c6f4-4782-9ebb-d160aa9a9308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjIwODQsIm5iZiI6MTcwNDQ2MTc4NCwicGF0aCI6Ii8yNzYxNzUxOC8yOTA0Mjg2NDItMGQ1YmFmMWMtYzZmNC00NzgyLTllYmItZDE2MGFhOWE5MzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEzMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNDc4M2U3NGNmYmViN2E0MzA1MDU2NzQ1NWQ5MTQ1MDA3NmJmN2NlNTAxYmFjOGJhMTQ2NjkxNTMzYzQ3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ASor-b1OSkIuGyPvyl0eH-4tgq9MwWxRAzCVyJuXkvM) ![image](https://private-user-images.githubusercontent.com/27617518/290428821-d1a5b684-592c-4038-8500-df5a40ba0487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjIwODQsIm5iZiI6MTcwNDQ2MTc4NCwicGF0aCI6Ii8yNzYxNzUxOC8yOTA0Mjg4MjEtZDFhNWI2ODQtNTkyYy00MDM4LTg1MDAtZGY1YTQwYmEwNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEzMzYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlY2ZkMzg3MzQzMGUxMWZiYTcyNzcxYzQwNWM3MDdmYTdiOGE5YzQxNDg5MmIyNzE2NjQ1ODVkNDVmMjg5YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ePsT6R1-wwcPOktTejc-m_Chq_thZcDlSz6NhOS9Rc)

遇到了同样的问题，batch size设置1也爆了

**Comment by LinB203** [comment]
当前许多人反馈OOM，然而我重新拉取代码并没有出现这个问题。我推测可能是系统环境有区别。我正在尝试解决这个问题。
[En] Currently a lot of people are giving feedback on OOM, however I'm not having this problem by re-pulling the code. I'm speculating that there may be a difference in the system environment. I am trying to resolve this issue.

**Comment by LinB203** [comment]
I uploaded `zero2_offload.json`, you can try `--deepspeed . /scripts/zero2_offload.json`, feel free to let me know of any updates.
