### ISSUE TITLE
The number of iterations is half what it should be

### ISSUE THREAD

**Issue by fightingaaa** [PKU-YuanGroup/Video-LLaVA#46]
Thanks for your great job, I met a question:The number of iterations is half what it should be.

The number of dataset is 665k+98K; num_train_epochs=1.0; per_device_train_batch_size=16;gpu=8. 
Iteration should be (665+98)*1.0/16/8=5.96k
However It show iteration is 2.48k

Looking forward to your reply, thanks in advance

**Comment by LinB203** [comment]
Do you use `gradient_accumulation_steps`?

**Comment by fightingaaa** [comment]
> Do you use `gradient_accumulation_steps`?

Yes, I follow the config provided
--gradient_accumulation_steps 2

**Comment by LinB203** [comment]
If `gradient_accumulation_steps` is set to 1, is the step count correct?

**Comment by fightingaaa** [comment]
> If `gradient_accumulation_steps` is set to 1, is the step count correct?

Yes，改成1之后 正常了。想请问下 这个参数变了之后，warm up 迭代数等参数 需要改变吗

**Comment by fightingaaa** [comment]
以及gpu 变成8之后的学习率这些参数 是对应*sqrt(2)吗，还是不变呢。有推荐的调整方案吗

**Comment by LinB203** [comment]
我的建议是不要改变默认的超参数。如果你的gpu少，或者batchsize少，那么增加`gradient_accumulation_steps`，保持全局batch size（per_device_train_batch_size x gradient_accumulation_steps x num_gpus）和默认设置不变即可。
[En] To train on fewer GPUs, you can reduce the per_device_train_batch_size and increase the gradient_accumulation_steps accordingly. Always keep the global batch size the same: per_device_train_batch_size x gradient_accumulation_steps x num_gpus.

**Comment by fightingaaa** [comment]
> 我的建议是不要改变默认的超参数。如果你的gpu少，或者batchsize少，那么增加`gradient_accumulation_steps`，保持全局batch size（`per_device_train_batch_size x gradient_accumulation_steps x num_gpus`）和默认设置不变即可。 [En] To train on fewer GPUs, you can reduce the `per_device_train_batch_size` and increase the `gradient_accumulation_steps` accordingly. Always keep the global batch size the same: `per_device_train_batch_size x gradient_accumulation_steps x num_gpus`.

好的；多谢。想再确认下 默认参数per_device_train_batch_size  16；gradient_accumulation_steps 2; num_gpus 4 是吧
