### ISSUE TITLE
deepspeed zero3 is not supported yet

### ISSUE THREAD

**Issue by valencebond** [PKU-YuanGroup/Video-LLaVA#48]
I try to replace the zero2.json with zero3.json in the pretraining stage.  But the model hangs and cannot train like zero2. Is it normal?

**Comment by LinB203** [comment]
Could you provide a screenshot to help us with this?

**Comment by valencebond** [comment]
hi @LinB203 thanks for your kind help. I just change zero2.json to zero3.json in scripts/v1_5/pretrain.sh . The model seems stuck at the model forward process, all gpus are 100% utilized. When I use zero2.json, everything is ok.

<img width="1573" alt="image" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/44313446/6f05f298-39f0-46fe-9757-4c33651d7acd">

**Comment by valencebond** [comment]
when I only using one gpu, zero3 setting works fine. Is there any suggestion ?

**Comment by LinB203** [comment]
It may be due to the NCCL communication error.
https://github.com/hiyouga/LLaMA-Factory/issues/1135
https://github.com/hiyouga/LLaMA-Factory/issues/1350

I have encountered similar problems on other nodes, and recently I have been working on code refactoring to try to solve it.

**Comment by valencebond** [comment]
> It may be due to the NCCL communication error. [hiyouga/LLaMA-Factory#1135](https://github.com/hiyouga/LLaMA-Factory/issues/1135) [hiyouga/LLaMA-Factory#1350](https://github.com/hiyouga/LLaMA-Factory/issues/1350)
> 
> I have encountered similar problems on other nodes, and recently I have been working on code refactoring to try to solve it.

Thank you for your help, I tried the suggested methods but the training still hangs.

**Comment by LinB203** [comment]
I will try to solve it.

**Comment by LinB203** [comment]
I will organize the code, support LoRA, support Zero3, and release more powerful models.

**Comment by valencebond** [comment]
> I will organize the code, support LoRA, support Zero3, and release more powerful models.

can you briefly give some guesses why zero3 is not working? Because the llava1.5 supports the zero3. Looking forward to an early resolution.

**Comment by LinB203** [comment]
From what I can surmise, this is a communication anomaly due to multiple gpu load imbalance. For example, when the batch size is 16, if the batch on gpu 0 is all IMAGE and there are IMAGE and VIDEO on gpu 1, then the load on the gpu is severely unbalanced at that point. I observed this phenomenon in the following issues.

https://github.com/microsoft/DeepSpeed/issues/2223
https://github.com/Lightning-AI/pytorch-lightning/issues/13498

**Comment by LinB203** [comment]
We reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh). Moreover, we provide zero2_offload.json, which can be used to train on A100-40G. But unfortunately we still can't use zero3, and we suspect that deepspeed doesn't support the load imbalance between GPUs very well. However this is not a problem with Video-LLaVA, so we close it.
