### ISSUE TITLE
bash scripts/v1_5/eval/eval_qa_msrvtt.sh

### ISSUE THREAD

**Issue by chajchaj** [PKU-YuanGroup/Video-LLaVA#50]
when running "bash scripts/v1_5/eval/eval_qa_msrvtt.sh", 
It reports the following errors, 
Can any gays tell me how to fix it ? 
----------------------------------------
completed_files: 0
incomplete_files: 72821
Error processing file 'v_video9632_17': Request timed out: HTTPSConnectionPool(host='api.chatanywhere.cn', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6975cac190>, 'Connection to api.chatanywhere.cn timed out. (connect timeout=600)'))
Error processing file 'v_video7010_0': Request timed out: HTTPSConnectionPool(host='api.chatanywhere.cn', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f68e4f5fac0>, 'Connection to api.chatanywhere.cn timed out. (connect timeout=600)'))

**Comment by LinB203** [comment]
This appears to be a network anomaly.
