### ISSUE TITLE
Much slower than llava training.

### ISSUE THREAD

**Issue by xmy0916** [PKU-YuanGroup/Video-LLaVA#51]
I found code here: https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/llava/model/llava_arch.py#L326
will cost a lot of time when batch size sets to 32.

maybe change the data sample func and  only image or video data is used in each batch will help increase training speed.

**Comment by LinB203** [comment]
Thank you for your contribution! We will update the code in the next version.
