### ISSUE TITLE
你好，训练这个模型需要多大的计算资源？

### ISSUE THREAD

**Issue by zhangyuereal** [PKU-YuanGroup/Video-LLaVA#53]
你好，训练这个模型需要多大的计算资源？

**Comment by LinB203** [comment]
目前我们用4 A100 80G。大约在55-60小时完成预训练和微调。然而目前的代价仍然难以承受，因此我们即将推出一个新版本，届时也许只需要一天时间即可完成。

[En] We currently use a 4 A100 80G. pre-training and fine tuning is done in about 55-60 hours. However the current cost is still unaffordable so we are about to release a new version which may then only take a day to complete.
