### ISSUE TITLE
推理代码放入循环中报错？

### ISSUE THREAD

**Issue by CaicaiJason** [PKU-YuanGroup/Video-LLaVA#54]
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/27617518/ad9da670-105b-41d0-9854-06e3cdfe3854)
单个视频推理都是OK的，只要把推理的代码放入循环中，就报IndexError，是什么情况呢？？

**Comment by LinB203** [comment]
我们重新编排了代码，现在已经可以支持了。
[En] We reorganize the code and it support now.
