### ISSUE TITLE
Consult a question in api demo

### ISSUE THREAD

**Issue by jdyjjj** [PKU-YuanGroup/Video-LLaVA#56]
This is a great job. After downloading the model locally, I encountered the problem shown in the following figure after running the sample code you provided.
code:
```
def main():
    disable_torch_init()
    video = 'video_path'
    inp = "Describe a person's characteristics"
    model_path = '/home/jdy/Video-LLaVA/LanguageBind/Video-LLaVA-7B'
    # model_path = 'LanguageBind/Video-LLaVA-7B'
    device = 'cuda'
    load_4bit, load_8bit = True, False
    model_name = get_model_name_from_path(model_path)
    tokenizer, model, processor, context_len = load_pretrained_model(model_path, None, model_name, load_8bit, load_4bit, device=device)
    video_processor = processor['video']
    ...
```
This is config.json in /home/jdy/LanguageBind/Video-LLaVA-7B
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/73057174/7791abc6-88e7-484e-8b59-326203d7ceec)

There is my error:
LanguageBind_Image does not have a file named preprocessor_config.json
```
OSError: /home/jdy/Video-LLaVA/LanguageBind/LanguageBind_Image does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//home/jdy/Video-LLaVA/LanguageBind/LanguageBind_Image/main' for available files.
```
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/73057174/586f09c2-3c5e-4cee-bd30-a3209da24b79)

If you could help me, I would be very grateful.

**Comment by LinB203** [comment]
Sorry for the misunderstanding due to our stupid implementation. You can change the path with this [line](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/llava/model/builder.py#L29).

We will update the code in parallel with the launch of Video-LLaVA 1.5, when the code robustness will be better.

**Comment by jdyjjj** [comment]
Thank you very much for your answer, but I still have one thing that I don't understand. I made the corresponding changes according to your guidance, but the error is still missing the preprocessor_config.json file.
Here is my code:
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/73057174/484fc38d-faea-4fcc-a23e-8e2d8adee571)
Here is error report:
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/73057174/7dc2e0b4-d3ac-44cc-a2dc-18c530837c82)
Any help would be of great help to me. God bless you!
