### ISSUE TITLE
Unable to access MSVD_Zero_Shot_QA

### ISSUE THREAD

**Issue by Leo-Yuyang** [PKU-YuanGroup/Video-LLaVA#59]
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/53007066/eee31f97-fe75-4640-ab45-e54d3a5f87b0)
Hi, thank you for your amazing work! When I was trying to download MSVD_Zero_Shot_QA, I found that the link is not valid anymore. 
![image](https://github.com/PKU-YuanGroup/Video-LLaVA/assets/53007066/ccfe2456-7dbd-4be0-9d1c-367a737b4a05)
Could you please release a new link for this dataset? Thank you for your support!

**Comment by LinB203** [comment]
You can download it through the PKU disk. Maybe the data violates the policy of Baidu disk.
