### ISSUE TITLE
Is there a way to fit Quantized version in Google Colab?

### ISSUE THREAD

**Issue by amrrs** [PKU-YuanGroup/Video-LLaVA#6]
Thanks so much! Google Colab offers a T4 with ~14ish GB of Graphics Memory, is there a way to fit this in there?

**Comment by LinB203** [comment]
We attempted but failed due to an out-of-memory error caused by the excessive number of tokens in the video. 
It is worth mentioning that we are currently exploring video token compression techniques, which are expected to provide improved performance in the near future. Thanks for your attention.
