### ISSUE TITLE
Are videos inferenced on the huggingface demo preserved in your internal storage?

### ISSUE THREAD

**Issue by avss8872** [PKU-YuanGroup/Video-LLaVA#62]
Thanks for your great research and a demo of the zero-shot video inference model.
I want to ask how the user uploaded video, inferenced by Video LLAVA demo, is handled.
(Demo link I used : https://huggingface.co/spaces/LanguageBind/Video-LLaVA)
Are videos saved in your lab's internal server or storage?
Actually, I mistook a name of a video and wrongly inferenced a privacy sensitive video which should not be released.
If it is preserved in your lab's storage, I want to get your help to delete it.

**Comment by LinB203** [comment]
Thanks for your attention. We do not preserve the video.
