### ISSUE TITLE
Visual tokens for each image

### ISSUE THREAD

**Issue by gordonhu608** [PKU-YuanGroup/Video-LLaVA#63]
Thanks for the great work. If I'm understanding correctly, Video-LLaVA is same as LLaVA in which one image is represented as 256 visual tokens (assuming 224 * 224). In your case, one video is sampled as 8 images. Then the visual token is 256 * 8 = 2048. I'm wondering how many VRAM does it need for for this one batch? And in your case, it's 256 batch size with 4* A100 80G, so may I wondering how much grad_iters you employed. Thanks.

**Comment by LinB203** [comment]
On 4 A100-80Gs, a batch takes up about 60-70G. The total data is 765k (665k llava-mix + 100k video), and we use batch size=128 for fine tuning, about 6k steps.
