### ISSUE TITLE
Possible to finetune on less A100 (80GB)?

### ISSUE THREAD

**Issue by orrzohar** [PKU-YuanGroup/Video-LLaVA#64]
Dear authors,

Thank you for your great work. I was wondering, is it possible to finetune on less A100 (80G) - perhaps 1 or 2?

Any advise on the matter?

Best,
Orr

**Comment by guzixian** [comment]
try --bit 8

**Comment by LinB203** [comment]
Hi, everyone, we reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).
