### ISSUE TITLE
如果我的训练集里面，40%的训练数据，全部是一问一答的文本信息， 这些数据没有视频、图片，vedio llava框架能训练吗？

### ISSUE THREAD

**Issue by awzhgw** [PKU-YuanGroup/Video-LLaVA#69]
我的训练集数据里面包含：

1.部分商品信息，包含图片、一问一答这种符合vedio llava框架的模型。

2. 一问一答的文本信息 。 （40%的训练样本）

那么vedio llava框架是否支持这种训练模式呢？ 就是图片、视频、文本（全部是文本一问一答）模式的混合训练呢？

**Comment by LinB203** [comment]
可以，因为video-llava的训练数据中就有40k的nlp数据。
[En] It can, because video-llava has 40k of nlp data in its training data.
