### ISSUE TITLE
valley pretraining data is used but valley instruction tuning data is not used

### ISSUE THREAD

**Issue by valencebond** [PKU-YuanGroup/Video-LLaVA#70]
i notice that the pretraining stage utilizes the valley pretraining data 702K (webvid2M), but the high-quality 73k instruction data collected by valley paper is not considered in the instruction tuning stage. Only videochatgpt video instruction data is used. What is the reason behind this choice ? Is it because of the poor quality of valley's instruction data?

**Comment by LinB203** [comment]
We just want to quickly verify that the baseline of video-llava works.
