### ISSUE TITLE
finetune with Video-LLaVA-7B，8bit，训练多个epoch但发现参数没有改变

### ISSUE THREAD

**Issue by guzixian** [PKU-YuanGroup/Video-LLaVA#71]
bash ./scripts/v1_5/finetune.sh

PROMPT_VERSION=v1
MODEL_VERSION="llama-2-7b-chat"
DATA_ROOT="/mnt/ssd_disk1/xnlin/LM/webvid/data"
deepspeed  --include='localhost:4'  --master_port=29502 llava/train/train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /home/workspace/zxgu/Video-LLaVA/LanguageBind/Video-LLaVA-7B \
    --version ${PROMPT_VERSION} \
    --X "Video" \
    --bit 8 \
    --data_path /mnt/ssd_disk1/xnlin/LM/webvid/text_2class_llava.json \
    --video_folder ${DATA_ROOT} \
    --video_tower /home/workspace/zxgu/Video-LLaVA/LanguageBind/LanguageBind_Video_merge \
    --pretrain_mm_mlp_adapter /home/workspace/zxgu/Video-LLaVA/LanguageBind/Video-LLaVA-Pretrain-7B/mm_projector.bin  \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_x_start_end False \
    --mm_use_x_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --bf16 False \
    --fp16 False \
    --output_dir ckpt/Video-LLaVA-7B_newfinetune \
    --num_train_epochs 50 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50 \
    --save_total_limit 4 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 16 \
    --report_to tensorboard \
    --lazy_preprocess True \
    --cache_dir "./cache_dir" \

config如下：
{
  "X": [
    "Video"
  ],
  "_name_or_path": "./lmsys/vicuna-7b-v1.5",
  "architectures": [
    "LlavaLlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "freeze_mm_mlp_adapter": false,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "image_aspect_ratio": "pad",
  "image_grid_pinpoints": null,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "mm_hidden_size": 1024,
  "mm_video_tower":"/home/workspace/zxgu/Video-LLaVA/LanguageBind/LanguageBind_Video_merge",
  "mm_projector_type": "mlp2x_gelu",
  "mm_use_x_patch_token": false,
  "mm_use_x_start_end": false,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "model_type": "llava",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.31.0",
  "tune_mm_mlp_adapter": false,
  "use_cache": true,
  "use_mm_proj": true,
  "vocab_size": 32000
}

如果将--model_name_or_path /home/workspace/zxgu/Video-LLaVA/LanguageBind/Video-LLaVA-7B \
改为"./lmsys/vicuna-7b-v1.5", 则会训练参数，这会是什么问题造成的呢？想基于您微调后的工作继续进行，希望得到你的回复XD.
（怀疑是Video-LLaVA-7B 的config设置错误导致）

**Comment by guzixian** [comment]
--lora_enable True \ 是不是int 8和4只能用lora参数加上去，原始模型用int 8和4加载finetune的话loss回传不了？

**Comment by LinB203** [comment]
我们不确定训练过程是否能用4 bit或8 bit。另外，我们目前正在验证LoRA的训练管道。相信不久后会释放新版本。
[En] We are not sure if the training process can be done with 4 bit or 8 bit. in addition, we are currently validating the LoRA training pipeline. I believe a new version will be released soon.

**Comment by LinB203** [comment]
Hi, we reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).

**Comment by guzixian** [comment]
> Hi, we reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).

感谢，牛掰。qlora理论上也是一样的吧。

**Comment by MATTbomerts** [comment]
您好，我也想基于官方已经微调之后的权重进行微调，但是LanguageBind/Video-LLaVA-7B文件中没有包含mm_projector.bin啊，请问您那边是什么样的结构啊？

**Comment by MATTbomerts** [comment]
您好，我也想基于官方微调之后的权重再进行微调，但是原本LanguageBind/Video-LLaVA-7B权重下已经没有单独的mm_projector.bin了，您是用的pretrain后的projector吗？以及您model_name_or_path这样的设置，不会报错KeyError: 'LlavaConfig'吗?
