### ISSUE TITLE
train lora task on llava video

### ISSUE THREAD

**Issue by dudulightricks** [PKU-YuanGroup/Video-LLaVA#72]
Hi,

I'm trying to train lora task on llava-video, but I get an error when trying to use peft on the model.
It happens in get_peft_model function, in this line:
"return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)"

Attached screenshot of the error. I only have 1 a100-80G and I want to finetune the video model for my task. This is the reason why I need to train lora. I will be glad for any help.

Thanks, 
David
<img width="923" alt="Screenshot 2024-01-14 at 17 56 45" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/53430514/b7c6c2a1-80e7-404e-adbf-b9bfd4661daf">

Training settings:
`deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /opt/llava-video-7b \
    --lora_enable True --lora_r 128 --lora_alpha 256 \
    --version v1 \
    --data_path /opt/data.json \
    --video_folder ${DATA_ROOT} \
    --image_folder ${DATA_ROOT} \
    --X "Video" "Image" \
    --video_tower LanguageBind/LanguageBind_Video_merge \
    --image_tower LanguageBind/LanguageBind_Image \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_x_start_end False \
    --mm_use_x_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/Video-LLaVA-7B \
    --num_train_epochs 2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "epoch" \
    --save_strategy "steps" \
    --save_steps 50 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --cache_dir "./cache_dir"
    --report_to wandb`

**Comment by LinB203** [comment]
We reorganize the code and support LoRA fine-tuning, checking [finetune_lora.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).
