### ISSUE TITLE
Can I deal with Chinese video? 

### ISSUE THREAD

**Issue by zhangyuereal** [PKU-YuanGroup/Video-LLaVA#75]
Thanks for your great work!
Can I deal with Chinese video? 
Ask questions in Chinese?

How to do this?

**Comment by LinB203** [comment]
Actually Video-LLaVA supports Chinese input, you just need to replace the input text with Chinese. Refer to our [API](https://github.com/PKU-YuanGroup/Video-LLaVA?tab=readme-ov-file#-api).

<img width="1145" alt="image" src="https://github.com/PKU-YuanGroup/Video-LLaVA/assets/62638829/246f5b5f-42b3-416e-af02-f83c677922b5">
