### ISSUE TITLE
Which Training Data to Use

### ISSUE THREAD

**Issue by boblee22** [PKU-YuanGroup/Video-LLaVA#80]
I saw that there are 7 json files in the training annotations. My understanding is

Stage 1 (pretraining):
1. llava_image_.json 
2. valley_.json

Stage 2 (finetuning):
1. llava_image_tune_.json
2. videochatgpt_tune_.json
3. nlp_tune.json

May I ask what `valley_llavaimage.json` and `videochatgpt_llavaimage_tune.json` are and when they are used?

Thanks a lot!

**Comment by LinB203** [comment]
Thanks for your attention.

We have reorganized the code, the `valley_llavaimage.json` and `videochatgpt_llavaimage_tune.json` you are talking about are the json used by the previous code. Please repull the code in the main branch and check out [pretrain.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/pretrain.sh) & [finetune.sh](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/main/scripts/v1_5/finetune.sh).

In fact, the current `llava_image_.json` and `valley_.json` correspond to the previous `valley_llavaimage.json`. `llava_image_tune_.json`, `videochatgpt_tune_.json`, and `nlp_tune.json` correspond to the previous `videochatgpt_llavaimage_tune.json`.

**Comment by boblee22** [comment]
Thanks so much! This is very useful!
