### ISSUE TITLE
OSError: LanguageBind/Video-LLaVA-7B does not appear to have a file named preprocessor_config.json

### ISSUE THREAD

**Issue by sandeepsingh** [PKU-YuanGroup/Video-LLaVA#81]
I am not able to load the model from hugging face. I am getting this error: 

OSError: LanguageBind/Video-LLaVA-7B does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/LanguageBind/Video-LLaVA-7B/main' for available files.

I am using this snippet from huggingface to load the model. 

from transformers import AutoProcessor
processor = AutoProcessor.from_pretrained("LanguageBind/Video-LLaVA-7B")

Requesting anyone who has resolved this error.

**Comment by LinB203** [comment]
For inference models please refer to our [API](https://github.com/PKU-YuanGroup/Video-LLaVA?tab=readme-ov-file#inference-for-video).

**Comment by sterzhang** [comment]
> For inference models please refer to our [API](https://github.com/PKU-YuanGroup/Video-LLaVA?tab=readme-ov-file#inference-for-video).

What's the different between this two models?
