### ISSUE TITLE
Where is model saved after instruction tuning?

### ISSUE THREAD

**Issue by orrzohar** [PKU-YuanGroup/Video-LLaVA#92]
I've run the instruction tuning bash script - but don't see a new checkpoint -- do you just overwrite the old checkpoint?

**Comment by LinB203** [comment]
do you finish the training？ the ckpt will save after the total training process. and could you post your command?

**Comment by orrzohar** [comment]
I ran:

```
DATA_ROOT="data"
HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 CUDA_VISIBLE_DEVICES=0,1,2,3 deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path train_json/train.json \
    --video_folder ${DATA_ROOT} \
    --image_folder ${DATA_ROOT} \
    --X "Video" "Image" \
    --video_tower LanguageBind/LanguageBind_Video_merge \
    --image_tower LanguageBind/LanguageBind_Image \
    --pretrain_mm_mlp_adapter checkpoints/Video-LLaVA-Pretrain-7B/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_x_start_end False \
    --mm_use_x_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/Video-LLaVA-7B \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --cache_dir "./cache_dir"
```

on 4xA100s. I didn't keep the print statements; but it ran until completion.
Where should the model be saved? just the old video-LLaVA overwritten?

**Comment by LinB203** [comment]
It will save in `./checkpoints/Video-LLaVA-7B`

**Comment by orrzohar** [comment]
I have re-run the job;
These are the last STDERR and STDOUT lines:


```
Job Details:

Last 10 lines of StdErr:
100%|█████████▉| 6703/6722 [55:49:52<09:27, 29.85s/it][h264 @ 0xf04d380] mmco: unref short failure
[h264 @ 0xf04d380] mmco: unref short failure
100%|█████████▉| 6709/6722 [55:52:56<06:37, 30.54s/it][mov,mp4,m4a,3gp,3g2,mj2 @ 0x670ad280] moov atom not found
[01:01:12] /github/workspace/src/video/video_reader.cc:83: ERROR opening: data/videochatgpt_tune/v_et029cxyEOs.mp4, Invalid data found when processing input
[h264 @ 0x12de8300] mmco: unref short failure
100%|█████████▉| 6710/6722 [55:53:26<06:06, 30.51s/it][h264 @ 0xbcec700] mmco: unref short failure
100%|█████████▉| 6711/6722 [55:53:56<05:32, 30.23s/it][h264 @ 0xee60140] mmco: unref short failure
[h264 @ 0xee60140] mmco: unref short failure
[h264 @ 0xee60140] mmco: unref short failure
100%|██████████| 6722/6722 [55:59:28<00:00, 29.99s/it]

Last 10 lines of StdOut:
{'loss': 0.8496, 'learning_rate': 0.0, 'epoch': 1.0}
{'train_runtime': 201568.4849, 'train_samples_per_second': 4.269, 'train_steps_per_second': 0.033, 'train_loss': 0.8576441739010549, 'epoch': 1.0}
[2024-02-04 01:08:21,937] [INFO] [launch.py:347:main] Process 2632130 exits successfully.
[2024-02-04 01:08:22,939] [INFO] [launch.py:347:main] Process 2632131 exits successfully.
[2024-02-04 01:08:22,939] [INFO] [launch.py:347:main] Process 2632127 exits successfully.
[2024-02-04 01:08:23,940] [INFO] [launch.py:347:main] Process 2632126 exits successfully.
[2024-02-04 01:08:23,940] [INFO] [launch.py:347:main] Process 2632128 exits successfully.
[2024-02-04 01:08:24,942] [INFO] [launch.py:347:main] Process 2632129 exits successfully.
[2024-02-04 01:08:24,942] [INFO] [launch.py:347:main] Process 2632132 exits successfully.
[2024-02-04 01:08:26,944] [INFO] [launch.py:347:main] Process 2632125 exits successfully.
```

**Comment by LinB203** [comment]
Could you check the path `./checkpoints/Video-LLaVA-7B`, is there any checkpoint?

**Comment by orrzohar** [comment]
Hi @LinB203,
Yes, with the following files:

config.json             
pytorch_model-00001-of-00002.bin  
pytorch_model.bin.index.json  
special_tokens_map.json 
 tokenizer.model     
training_args.bin
generation_config.json  
pytorch_model-00002-of-00002.bin  runs                          
tokenizer_config.json    
trainer_state.json

Doesn't the model also need the weights for the LanguageBind encoders + LLaMA? I don't see those locally. Are these the weights for the entire model?

Best,
Orr

**Comment by LinB203** [comment]
Exactly. All models (vision encoder, mlp adapter, llm) are saved in one checkpoint.

**Comment by orrzohar** [comment]
Oh OK. 
By the way, the model downloaded via transformers has a different structure:

models-LanguageBind-Video-LLaVA-7B \  snapshots \ 0d50857822b04a6f3a7d34d1cce5065d42fc6008:

config.json  
generation_config.json  
pytorch_model-00001-of-00002.bin  
pytorch_model-00002-of-00002.bin  
pytorch_model.bin.index.json


And are you sure this is the instruction fine-tuned model and not the pretrained one? 
Best,
Orr

**Comment by LinB203** [comment]
> Oh OK. By the way, the model downloaded via transformers has a different structure:
> 
> models-LanguageBind-Video-LLaVA-7B \ snapshots \ 0d50857822b04a6f3a7d34d1cce5065d42fc6008:
> 
> config.json generation_config.json pytorch_model-00001-of-00002.bin pytorch_model-00002-of-00002.bin pytorch_model.bin.index.json
> 
> And are you sure this is the instruction fine-tuned model and not the pretrained one? Best, Orr

Sure, for pretrained checkpoint, it only save the mlp adapter (mm_projector.bin).

**Comment by orrzohar** [comment]
OK, I wanted to make sure because I am getting some discrepancies between reported and evaluated values for this checkpoint (I will continue discussing that in that issue).

Thank you!
