### ISSUE TITLE
Offline load checkpoint error

### ISSUE THREAD

**Issue by DemoGit4LIANG** [PKU-YuanGroup/Video-LLaVA#93]
Hi~ I have download the LanguageBind/Video-LLaVA-7B weights and set model_path correspondingly, but encounters the follow errors when I launch the chat because my server cannot access huggingface:

===> pretrained_model_name_or_path: /data/xxx/weights/video_llava
===> pretrained_model_name_or_path: LanguageBind/LanguageBind_Image
OSError: We couldn't connect to 'https://huggingface.co' to load this file ...

So could you teach me how to set the offline weights of LanguageBind/LanguageBind_Image and LanguageBind/LanguageBind_Video_merge ? I tried my ways but failed.

**Comment by LinB203** [comment]
Refer to this issue.
https://github.com/PKU-YuanGroup/Video-LLaVA/issues/57

**Comment by DemoGit4LIANG** [comment]
> Refer to this issue. #57

Thanks. It works.
