### ISSUE TITLE
Clarification question about model training

### ISSUE THREAD

**Issue by boblee22** [PKU-YuanGroup/Video-LLaVA#94]
I saw that during pretraining, `tune_mm_mlp_adapter` is True, and only `mm_projector` is trained, the other parameters are frozen. During fine-tuning, all the model parameters are trained. Is this correct?

A follow-up question: When `tune_mm_mlp_adapter` is False, `mm_projector` is saved in `trainer._save_checkpoint`. But this is not intuitive to me. Does this saving only happen in the fine-tuning stage?

**Comment by LinB203** [comment]
The pretraining stage trains only the `mlp_adapter`. The fine-tuning stage trains the `mlp_adapter`, LLM but **not the image encoder.**
